---
- name: Installing chrony
  apt:
    update_cache: true
    cache_valid_time: "3600"
    state: present
    name: chrony

- name: Templating out chrony config file
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony
    
- name: Making sure chrony service is enabled and started
  service:
    name: chronyd
    enabled: yes
    state: started
